name: Manually deployment of remote state

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The name of branch"
        required: true
        type: string
permissions:
  contents: read
  id-token: write
  pull-requests: write
  actions: read
  security-events: write
env:
  terraform_dir: "examples/remote_state"
jobs:
  terraform:
    name: Terraform Init, Fmt, Validate, Plan, Apply, and Infracost
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Pobierz repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Potrzebne, aby pobrać pełną historię repozytorium

      # Krok 2: Konfiguracja poświadczeń AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Krok 3: Instalacja Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Krok 4: Planowanie Terraform dla aktualnego PR
      - name: Terraform Plan
        working-directory: ${{ env.terraform_dir }}
        run: terraform plan -out=tfplan-pr

      # Krok 5: Terraform Apply (z opcją auto-approve, aby nie wymagać interakcji użytkownika)
      - name: Terraform Apply
        working-directory: ${{ env.terraform_dir }}
        run: terraform apply -input=false -auto-approve tfplan-pr
